import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavBar from '@/app/ui/nav-bar'
import { auth0 } from "./lib/auth0";
import Landing from "./ui/landing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SocialApp",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth0.getSession();

  if (!session) {
    return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col gap-4 p-8`}>
        <Landing />
        <p><a href="/auth/login" className="rounded bg-teal-800 p-2">Log in</a></p>
      </body>
      </html>
    )
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen`}>
        <NavBar />
        <div className="flex-1 p-4 sm:p-8 sm:pl-12 sm:ml-64 mt-20 sm:mt-4 overflow-x-hidden">
          <div className="max-w-screen-xl mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
